---
title: "Expected Value"
format: html
from: markdown+emoji
filters: 
  - shinylive
---

# What is Expectation?

The expected value in statistics is the value we'd expect to get if we run an experiment a bunch of times. It can be thought of as a weighted average. It's the sum of the probability of an outcome times the value of the outcome for all possible outcomes.

An example by [Statistics by Jim](https://statisticsbyjim.com/probability/expected-value/): If a contestant on a game show has a 50% chance of winning \$100, 40% chance of \$500, or 10% chance of losing \$100, then the expected value from a bunch of contestants playing would be: 
$$
0.5 * 100 + 0.4 * 500 + .1 * (-100) = $240
$$


# What are Moments?

Moments are parameters that characterize a distribution. The help us understand its shape and position. The first moment, or mean, represents the expected value of a random variable (see :arrow_up:). If we repeat an experiment many times, the average of our observations will converge to the mean (under the Law of Large Numbers).

The interactive graphic below shows how changing two moments, mean and variance, affect the appearance of a distribution.

```{shinylive-python}
#| standalone: true
#| viewerHeight: 660
from shiny.express import input, render, ui
from shiny import reactive
import pandas as pd
from scipy.stats import norm, gamma, geom
import plotly.express as px
from shinywidgets import render_plotly

# Show user a dropdown to select the distribution
ui.input_select(
    id='distribution',
    label='Select distribution:',
    choices=[
        'Normal',
        'Gamma (not ready yet)',
        'Geometric (not ready yet)'
    ],
    selected='Normal',
    width='200px'   
)

# Show user sliders for mean and variance
ui.input_slider(
    id='firstmoment',
    label='Select the first moment: ',
    min=0,
    max=100,
    value=10,
    step=1
)
ui.input_slider(
    id='secondmoment',
    label='Select the second moment:',
    min=0,
    max=10,
    value=10,
    step=1
)

# Helper functions to generate random variates based on
@reactive.calc
def get_normal_data():
    mean = input.firstmoment()
    std_dev = input.secondmoment()
    data = norm.rvs(loc=mean, scale=std_dev, size=1000)
    data_df = pd.DataFrame(data, columns=['Value'])
    skew, kurtosis = 0, 0 # always for normal distribution
    return data_df, skew, kurtosis
 
# Plot the data as histogram with fit line
@render_plotly
def plot_hist():
    if input.distribution() == 'Normal':
        # get normal data
        data, skew, kurt = get_normal_data()
        fig = px.histogram(data, x="Value",title="Normal Distribution", nbins=30)
        fig.update_xaxes(range=[1,100])
        return fig
    if input.distribution() == 'Gamma (not ready yet)':
        pass
    if input.distribtuion() == 'Geometric (not ready yet)':
        pass

# show skew and kurtosis in value box?

```